
name: variational-quantum-pde
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - qiskit>=0.45.0
      - qiskit-aer>=0.13.0
      - numpy>=1.24.0
      - scipy>=1.10.0
      - matplotlib>=3.7.0
      - tqdm>=4.65.0
      - jupyter>=1.0.0
      - pandas>=2.0.0
      - fipy>=3.4.0
